name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: |
          xcode-select -s /Applications/Xcode_26.0.1.app
          ./build.sh

      - run: zip -r NotEnoughResins.zip build/NotEnoughResins.app

      - uses: softprops/action-gh-release@v2
        with:
          files: NotEnoughResins.zip
