name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - run: ./build.sh

      - uses: softprops/action-gh-release@v2
        with:
          files: build/NotEnoughResins.app