name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-26
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: |
          sudo xcode-select -s /Applications/Xcode_26.0.1.app
          ./build.sh

      - run: zip -r NotEnoughResins.zip build/NotEnoughResins.app

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: NotEnoughResins.zip

      - uses: softprops/action-gh-release@v2
        with:
          files: NotEnoughResins.zip
